[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
prost = "0.11.2"
tonic = "0.8.2"

[build-dependencies]
tonic-build = "0.8.2"
